export type Equip = "none" | "pushupBar" | "couch";
export type Muscle = "mell" | "hát" | "váll" | "kar" | "core" | "láb" | "cardio" | "mobilitás";

export type Exercise = {
  id: string;
  name: string;
  muscles: Muscle[];
  equip: Equip[];
  level: 1 | 2 | 3; // 1=kezdő, 2=középhaladó, 3=haladó
  desc: string;          // mire jó
  cues: string[];        // technikai tippek
  regression?: string;   // könnyítés
  progression?: string;  // nehezítés
  unit: "ismétlés" | "másodperc" | "perc";
  // free-exercise-db (yuhonas) ID a vizuális 2-frame animációhoz
  animId?: string;
};

export const EXERCISES: Exercise[] = [
  // ===== MELL / TRICEPSZ / VÁLL (PUSH) =====
  {
    id: "incline-pushup",
    name: "Ferde fekvőtámasz (kéz a kanapén)",
    muscles: ["mell", "váll", "kar", "core"],
    equip: ["couch"],
    level: 1,
    desc: "A klasszikus fekvőtámasz legkönnyebb változata, ideális kezdésre.",
    cues: [
      "Kezek vállszélességben a kanapé szélén.",
      "Test egyenes – tarkó, hát, fenék, sarok egy vonalban.",
      "Mellkas érintse a kanapé szélét lent.",
      "Könyök kb. 45°-ban hátra, ne tárd ki teljesen oldalra.",
    ],
    regression: "Magasabb felület (pl. konyhapult).",
    progression: "Lépj át sima fekvőtámaszra.",
    unit: "ismétlés",
  },
  {
    id: "knee-pushup",
    name: "Térdelő fekvőtámasz",
    muscles: ["mell", "kar", "core"],
    equip: ["none"],
    level: 1,
    desc: "Átmenet a ferdéből a teljes fekvőtámaszba.",
    cues: [
      "Térd–csípő–váll egyenes vonal.",
      "Hasizom feszül, ne lógjon a derék.",
      "Lassan le, robbanékonyan fel.",
    ],
    progression: "Sima fekvőtámasz.",
    unit: "ismétlés",
  },
  {
    id: "pushup",
    name: "Fekvőtámasz",
    muscles: ["mell", "váll", "kar", "core"],
    equip: ["none", "pushupBar"],
    level: 2,
    desc: "Alap mozgás, mellet, vállat, tricepszet és core-t épít.",
    cues: [
      "Pushup baron mélyebbre tudsz menni – nagyobb terjedelem, jobb fejlődés.",
      "Lapocka behúzva lent, kinyomva fent.",
      "Ne ess sebességbe – 2 mp le, 1 mp fel.",
    ],
    regression: "Térdelő vagy ferde.",
    progression: "Diamond, decline (láb a kanapén), tempó-fekvőtámasz.",
    unit: "ismétlés",
  },
  {
    id: "decline-pushup",
    name: "Lejtős fekvőtámasz (láb a kanapén)",
    muscles: ["mell", "váll", "kar", "core"],
    equip: ["couch", "pushupBar"],
    level: 2,
    desc: "A vállra és felső mellre tol több terhelést.",
    cues: ["Csípő ne lógjon, törzs feszes.", "Mellkas mélyre, nem orr."],
    progression: "Pike pushup.",
    unit: "ismétlés",
  },
  {
    id: "diamond-pushup",
    name: "Gyémánt fekvőtámasz",
    muscles: ["kar", "mell"],
    equip: ["none"],
    level: 2,
    desc: "Triceps fókuszú változat.",
    cues: ["Hüvelyk- és mutatóujjak gyémántot formálnak.", "Könyök közel a testhez."],
    regression: "Térdelő gyémánt.",
    unit: "ismétlés",
  },
  {
    id: "pike-pushup",
    name: "Pike fekvőtámasz",
    muscles: ["váll", "kar"],
    equip: ["none", "pushupBar"],
    level: 2,
    desc: "Vállra fókuszáló, állásos fejnyomás-helyettesítő.",
    cues: ["Csípő magasra – fordított V.", "Fejtetőt vidd a talaj felé."],
    progression: "Emelt lábú pike (láb a kanapén).",
    unit: "ismétlés",
  },
  {
    id: "couch-dip",
    name: "Tricepsz dip (kanapé)",
    muscles: ["kar", "váll"],
    equip: ["couch"],
    level: 1,
    desc: "Triceps izoláció a kanapé szélén.",
    cues: [
      "Tenyér a kanapé szélén, ujjak előrenéznek.",
      "Könyök hátra mutat, ne kifelé.",
      "Csípő közel a kanapéhoz.",
    ],
    progression: "Pushup bar dip (két bar között, lábak előre).",
    unit: "ismétlés",
  },

  // ===== HÚZÁS (PULL) – kanapéval =====
  {
    id: "couch-row",
    name: "Kanapé alatti fordított evezés",
    muscles: ["hát", "kar"],
    equip: ["couch"],
    level: 2,
    desc: "Egyetlen otthoni eszközös húzómozgás – a kanapé alá fekszel, és felhúzod magad a peremnél fogva. Stabil kanapénál működik (nehéz, ne boruljon).",
    cues: [
      "Feküdj a kanapé elé, kezek a párnák alatti keményebb peremen vagy a kanapé alvázán.",
      "Test egyenes, sarok a talajon.",
      "Lapockát húzd hátra-le, mellkast vidd a perem felé.",
    ],
    regression: "Térdelő evezés (térd hajlítva).",
    progression: "Lábat fel a kanapéra a teljes vízszintes húzáshoz.",
    unit: "ismétlés",
  },
  {
    id: "doorway-row",
    name: "Ajtókeret húzás (egykezes)",
    muscles: ["hát", "kar"],
    equip: ["none"],
    level: 1,
    desc: "Ha a kanapé nem alkalmas evezésre: állj az ajtókeret mellé, fogd meg, és húzd magad a keret felé.",
    cues: ["Lábak közel a kerethez.", "Dőlj hátra egyenes testtel, húzd magad vissza."],
    progression: "Egylábú változat.",
    unit: "ismétlés",
  },
  {
    id: "superman",
    name: "Superman",
    muscles: ["hát", "core"],
    equip: ["none"],
    level: 1,
    desc: "Hátsó lánc aktiváció – fontos az ülőmunka után.",
    cues: ["Hasra fekszel, kar és láb egyszerre emelve.", "Tartás 1–2 mp fent."],
    unit: "ismétlés",
  },
  {
    id: "ytw",
    name: "Y-T-W lapocka aktiváció",
    muscles: ["hát", "váll", "mobilitás"],
    equip: ["none"],
    level: 1,
    desc: "Görnyedés ellen, vállhátsó és középső csuklya aktiváció.",
    cues: ["Hason fekve, hüvelykujj felfelé.", "Y, T, W formák lassan."],
    unit: "ismétlés",
  },

  // ===== LÁB =====
  {
    id: "squat",
    name: "Saját súlyos guggolás",
    muscles: ["láb", "core"],
    equip: ["none"],
    level: 1,
    desc: "Combra, fenékre alap mozgás.",
    cues: [
      "Talp tövénél stabilan, sarok a talajon.",
      "Térd a lábujj irányába, ne befelé.",
      "Mély, de gerincet egyenesen tartva.",
    ],
    progression: "Lassú tempó (3-1-1), majd bolgár szplitt.",
    unit: "ismétlés",
  },
  {
    id: "couch-squat",
    name: "Kanapéra leülős guggolás",
    muscles: ["láb"],
    equip: ["couch"],
    level: 1,
    desc: "Kezdő guggolás-tanuláshoz, érintsd a kanapét fenékkel és állj fel.",
    cues: ["Csípő hátra, mintha leülnél.", "Ne huppanj, csak érintsd."],
    unit: "ismétlés",
  },
  {
    id: "split-squat",
    name: "Bolgár szplitt guggolás (hátsó láb kanapén)",
    muscles: ["láb", "core"],
    equip: ["couch"],
    level: 2,
    desc: "Egylábas erősítő, javítja az egyensúlyt is.",
    cues: ["Mellső térd a lábujjak fölött.", "Törzs előre dől kissé.", "10 oldalanként."],
    unit: "ismétlés",
  },
  {
    id: "lunge",
    name: "Kitörés",
    muscles: ["láb", "core"],
    equip: ["none"],
    level: 1,
    desc: "Egylábas lábmunka és stabilitás.",
    cues: ["Hosszú lépés.", "Hátsó térd közel a talajhoz.", "Törzs egyenes."],
    progression: "Sétáló kitörés, ugró kitörés.",
    unit: "ismétlés",
  },
  {
    id: "glute-bridge",
    name: "Csípőemelés (glute bridge)",
    muscles: ["láb", "core"],
    equip: ["none"],
    level: 1,
    desc: "Fenékizom aktiváció – ülőmunka után aranyat ér.",
    cues: ["Hanyatt, térd hajlítva.", "Csípőt szorítsd ki, tartsd 1 mp-et."],
    progression: "Egylábú híd.",
    unit: "ismétlés",
  },
  {
    id: "calf-raise",
    name: "Vádli emelés",
    muscles: ["láb"],
    equip: ["none"],
    level: 1,
    desc: "Vádli erősítés.",
    cues: ["Lassan fel, lassan le, teljes terjedelem."],
    progression: "Egylábú, lépcső peremén.",
    unit: "ismétlés",
  },
  {
    id: "wall-sit",
    name: "Fal melletti ülés",
    muscles: ["láb"],
    equip: ["none"],
    level: 1,
    desc: "Izotóniás láberősítő – égeti a combot.",
    cues: ["Hát a falon, comb párhuzamos a talajjal."],
    unit: "másodperc",
  },

  // ===== CORE =====
  {
    id: "plank",
    name: "Plank (alkartámasz)",
    muscles: ["core"],
    equip: ["none"],
    level: 1,
    desc: "Statikus core erő.",
    cues: ["Könyök váll alatt.", "Fenék ne lógjon, ne menjen fel.", "Hasizom feszül."],
    progression: "Egylábú plank.",
    unit: "másodperc",
  },
  {
    id: "side-plank",
    name: "Oldalsó plank",
    muscles: ["core"],
    equip: ["none"],
    level: 1,
    desc: "Oldalsó core (ferde hasizmok).",
    cues: ["Test egyenes vonal.", "Csípő ne ess le."],
    unit: "másodperc",
  },
  {
    id: "deadbug",
    name: "Dead bug",
    muscles: ["core"],
    equip: ["none"],
    level: 1,
    desc: "Biztonságos hasizom — derékkímélő.",
    cues: ["Derék a talajra szorítva.", "Ellentétes kar és láb lassan."],
    unit: "ismétlés",
  },
  {
    id: "leg-raise",
    name: "Lábemelés (hanyatt)",
    muscles: ["core"],
    equip: ["none"],
    level: 2,
    desc: "Alsó hasizom fókusz.",
    cues: ["Derék a talajon végig.", "Térd hajlított = könnyebb."],
    progression: "Nyújtott lábú emelés.",
    unit: "ismétlés",
  },
  {
    id: "hollow-hold",
    name: "Hollow hold",
    muscles: ["core"],
    equip: ["none"],
    level: 2,
    desc: "Gimnasztikai core alap.",
    cues: ["Derék a talajon!", "Kar és láb kicsit a föld fölött."],
    unit: "másodperc",
  },
  {
    id: "mountain-climber",
    name: "Mountain climber",
    muscles: ["core", "cardio"],
    equip: ["none"],
    level: 1,
    desc: "Core + pulzus.",
    cues: ["Plank pozíció.", "Térdet a mellkashoz váltva."],
    unit: "másodperc",
  },
  {
    id: "bicycle",
    name: "Kerékpárzás (bicycle crunch)",
    muscles: ["core"],
    equip: ["none"],
    level: 1,
    desc: "Ferde hasizom.",
    cues: ["Lassan, koncentráltan, ne rángasd a nyakat."],
    unit: "ismétlés",
  },

  // ===== CARDIO / STAMINA =====
  {
    id: "jumping-jack",
    name: "Terpesz-zár (jumping jack)",
    muscles: ["cardio"],
    equip: ["none"],
    level: 1,
    desc: "Bemelegítés és stamina alap.",
    cues: ["Folyamatos ritmus, talp puhán."],
    unit: "másodperc",
  },
  {
    id: "high-knee",
    name: "Magas térd futás helyben",
    muscles: ["cardio", "láb"],
    equip: ["none"],
    level: 1,
    desc: "Pulzust gyorsan felviszi.",
    cues: ["Térd csípő magasság."],
    unit: "másodperc",
  },
  {
    id: "butt-kick",
    name: "Sarokemelés helyben",
    muscles: ["cardio"],
    equip: ["none"],
    level: 1,
    desc: "Pulzus + comb hátsó.",
    cues: ["Sarok érintse a feneket."],
    unit: "másodperc",
  },
  {
    id: "shadow-box",
    name: "Árnyékboksz",
    muscles: ["cardio", "core"],
    equip: ["none"],
    level: 1,
    desc: "Szórakoztató pulzusemelő, váll-állóképesség.",
    cues: ["Lazán mozogj, ütések sorozatban."],
    unit: "másodperc",
  },
  {
    id: "squat-jump",
    name: "Guggolás ugrással",
    muscles: ["láb", "cardio"],
    equip: ["none"],
    level: 2,
    desc: "Robbanékony láb + pulzus.",
    cues: ["Puhán érkezz, térd ne dőljön befelé."],
    unit: "ismétlés",
  },
  {
    id: "burpee",
    name: "Burpee",
    muscles: ["cardio", "mell", "láb", "core"],
    equip: ["none"],
    level: 2,
    desc: "Teljes test, brutális stamina építő.",
    cues: [
      "Guggolás → kéz a földre → ugrás hátra plankbe → fekvőtámasz (opcionális) → ugrás vissza → ugrás fel.",
      "Kezdőként pushup nélkül és lépéssel a plankbe.",
    ],
    regression: "Step-back burpee pushup nélkül.",
    unit: "ismétlés",
  },

  // ===== MOBILITÁS / NYÚJTÁS =====
  {
    id: "cat-cow",
    name: "Macska-tehén",
    muscles: ["mobilitás", "core"],
    equip: ["none"],
    level: 1,
    desc: "Gerincmobilitás – ülés ellen.",
    cues: ["Lassú lélegzés, görnyedés-homorítás."],
    unit: "ismétlés",
  },
  {
    id: "world-greatest",
    name: "World's greatest stretch",
    muscles: ["mobilitás"],
    equip: ["none"],
    level: 1,
    desc: "Csípő, ágyék, mellkas egyben.",
    cues: ["Kitörés, törzsforgatás, nyitás felfelé."],
    unit: "ismétlés",
  },
  {
    id: "hip-flexor-stretch",
    name: "Csípőhajlító nyújtás",
    muscles: ["mobilitás"],
    equip: ["none"],
    level: 1,
    desc: "Sok ülés után kötelező.",
    cues: ["Térdelő kitörés, csípőt told előre, fenék szorítva."],
    unit: "másodperc",
  },
  {
    id: "thoracic-rotation",
    name: "Mellkasi gerinc forgatás",
    muscles: ["mobilitás"],
    equip: ["none"],
    level: 1,
    desc: "Felsőhát mobilitás.",
    cues: ["Négykézláb, egy kéz tarkón, könyök fel."],
    unit: "ismétlés",
  },
  {
    id: "walk",
    name: "Séta (kint vagy lakásban)",
    muscles: ["cardio"],
    equip: ["none"],
    level: 1,
    desc: "A legfontosabb napi mozgás. Cél: 7–10 ezer lépés.",
    cues: ["Munka közben 2 óránként 5 perc séta.", "Lehetőleg friss levegőn."],
    unit: "perc",
  },
];

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}
